export const HELP_TEXT = [
  'GetThreads Bot',
  '',
  '傳送連結即可自動儲存內容與評論：',
  'X / Threads / Reddit / YouTube / GitHub',
  '微博 / B站 / 小紅書 / 抖音 / 任何網頁',
  '',
  '指令：',
  '/search <查詢> — 網頁搜尋',
  '/monitor <關鍵字> — 跨平台搜尋提及',
  '/timeline @用戶 — 抓取用戶最近貼文',
  '/ask <問題> — 用知識庫回答問題',
  '/knowledge — 知識庫總覽（缺口/技能/偏好/分析）',
  '/explore <主題> — 知識探索（推薦/簡報/對比）',
  '/digest — 知識報告（精華/蒸餾/整合）',
  '/discover <關鍵字> — GitHub 專案探索（無參數=熱門）',
  '/learn — Vault 學習（分類規則/重新分類/翻譯）',
  '/reprocess <路徑> — 重新 AI 豐富筆記',
  '/retry — 重試失敗的連結',
  '/subscribe @用戶 — 訂閱自動追蹤',
  '/quality — Vault 品質報告',
  '/status — Bot 狀態與本次儲存',
  '/help — 顯示此說明',
].join('\n');

export const BOT_COMMANDS_MENU = [
  { command: 'start', description: '顯示 Bot 說明' },
  { command: 'search', description: '網頁搜尋' },
  { command: 'monitor', description: '跨平台搜尋提及' },
  { command: 'timeline', description: '抓取用戶最近貼文' },
  { command: 'ask', description: '用知識庫回答問題' },
  { command: 'knowledge', description: '知識庫總覽' },
  { command: 'explore', description: '知識探索（推薦/簡報/對比）' },
  { command: 'digest', description: '知識報告' },
  { command: 'discover', description: 'GitHub 專案探索' },
  { command: 'learn', description: 'Vault 學習與分類' },
  { command: 'reprocess', description: '重新 AI 豐富筆記' },
  { command: 'retry', description: '重試失敗的連結' },
  { command: 'subscribe', description: '訂閱自動追蹤' },
  { command: 'quality', description: 'Vault 品質報告' },
  { command: 'status', description: 'Bot 狀態' },
  { command: 'help', description: '顯示說明' },
];
