export const HELP_TEXT = [
  'GetThreads Bot',
  '',
  '傳送連結即可自動儲存內容與評論：',
  'X / Threads / Reddit / YouTube / GitHub',
  '微博 / B站 / 小紅書 / 抖音 / 任何網頁',
  '',
  '指令：',
  '/search <查詢> — 網頁搜尋',
  '/monitor <關鍵字> — 跨平台搜尋提及',
  '/timeline @用戶 — 抓取用戶最近貼文',
  '/analyze — 深度分析 Vault 知識',
  '/knowledge — 查看知識庫摘要',
  '/recommend <主題> — 推薦相關筆記',
  '/brief <主題> — 主題知識簡報',
  '/compare <A> vs <B> — 實體對比',
  '/gaps — 知識缺口分析',
  '/skills — 高密度主題 Skill 建議',
  '/preferences — 用戶偏好模型',
  '/distill — 知識蒸餾報告',
  '/consolidate — 整合近期知識，發現跨筆記洞察',
  '/ask <問題> — 用知識庫回答問題',
  '/discover <關鍵字> — GitHub 專案探索',
  '/trending — 每日熱門專案掃描',
  '/reprocess <路徑> — 重新 AI 豐富現有筆記',
  '/retry — 重試失敗的連結',
  '/subscribe @用戶 — 訂閱自動追蹤新內容',
  '/quality — Vault 品質報告',
  '/digest — 近期知識精華摘要',
  '/recent — 本次啟動已儲存的內容',
  '/status — Bot 運行狀態',
  '/learn — 重新掃描 Vault 更新分類',
  '/reclassify — 重新分類所有筆記',
  '/translate — 批次翻譯英文/簡中筆記',
  '/help — 顯示此說明',
].join('\n');

export const BOT_COMMANDS_MENU = [
  { command: 'start', description: '顯示 Bot 說明' },
  { command: 'search', description: '網頁搜尋' },
  { command: 'monitor', description: '跨平台搜尋提及' },
  { command: 'timeline', description: '抓取用戶最近貼文' },
  { command: 'analyze', description: '深度分析 Vault 知識' },
  { command: 'knowledge', description: '查看知識庫摘要' },
  { command: 'recommend', description: '推薦相關筆記' },
  { command: 'brief', description: '主題知識簡報' },
  { command: 'compare', description: '實體對比' },
  { command: 'gaps', description: '知識缺口分析' },
  { command: 'skills', description: '高密度主題 Skill 建議' },
  { command: 'preferences', description: '用戶偏好模型' },
  { command: 'distill', description: '知識蒸餾報告' },
  { command: 'consolidate', description: '整合近期知識洞察' },
  { command: 'ask', description: '用知識庫回答問題' },
  { command: 'discover', description: 'GitHub 專案探索' },
  { command: 'trending', description: '每日熱門專案掃描' },
  { command: 'reprocess', description: '重新 AI 豐富現有筆記' },
  { command: 'retry', description: '重試失敗的連結' },
  { command: 'subscribe', description: '訂閱自動追蹤新內容' },
  { command: 'quality', description: 'Vault 品質報告' },
  { command: 'digest', description: '近期知識精華摘要' },
  { command: 'recent', description: '本次已儲存的內容' },
  { command: 'status', description: 'Bot 運行狀態' },
  { command: 'learn', description: '重新掃描 Vault 更新分類' },
  { command: 'reclassify', description: '重新分類所有筆記' },
  { command: 'translate', description: '批次翻譯英文/簡中筆記' },
  { command: 'help', description: '顯示說明' },
];

